initFields:
  bugs:
    url: "https://github.com/facebookresearch/Mephisto/issues"
  homepage: "https://github.com/facebookresearch/Mephisto.git"
  license: MIT
  main: build/bundle.js
  repository:
    type: git
    url: "git+https://github.com/facebookresearch/Mephisto.git"
  source: src/index.js

initScope: annotated

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  "@docusaurus/utils-validation@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "@docusaurus/core@*":
    dependencies:
      "@docusaurus/mdx-loader": "latest"
  "@docusaurus/mdx-loader@*":
    dependencies:
      "tslib": "latest"
  "html-minifier-terser@*":
    dependencies:
      "acorn": "latest"
