initFields:
  bugs:
    url: "https://github.com/facebookresearch/Mephisto/issues"
  homepage: "https://github.com/facebookresearch/Mephisto.git"
  license: MIT
  main: build/bundle.js
  repository:
    type: git
    url: "git+https://github.com/facebookresearch/Mephisto.git"
  source: src/index.js

initScope: annotated

yarnPath: ".yarn/releases/yarn-berry.cjs"
