initFields:
  bugs:
    url: "https://github.com/facebookresearch/Mephisto/issues"
  homepage: "https://github.com/facebookresearch/Mephisto.git"
  license: MIT
  main: build/bundle.js
  repository:
    type: git
    url: "git+https://github.com/facebookresearch/Mephisto.git"
  source: src/index.js

initScope: annotated

packageExtensions:
  "@docusaurus/core@*":
    dependencies:
      "@docusaurus/mdx-loader": latest
  "@docusaurus/mdx-loader@*":
    dependencies:
      tslib: latest
  "@docusaurus/utils-validation@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  html-minifier-terser@*:
    dependencies:
      acorn: latest

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
