name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: black
        uses: pre-commit/action@v2.0.0
        with:
          extra_args: black --all-files
      - name: prettier
        uses: pre-commit/action@v2.0.0
        with:
          extra_args: prettier --all-files
